"""
Django settings for ProyectoAlbergueDR project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ga_(0e*eau0gzt1ojekv67q9kkw4cs7burmqi$-7+p1q_fbw9$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['AlbergueDivinoRedentor.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'farmacia.apps.FarmaciaConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'ProyectoAlbergueDR.urls'

import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
             BASE_DIR / 'templates',
             os.path.join(BASE_DIR, 'Farmacia', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProyectoAlbergueDR.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

    
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


##PARA LA MEJORA DEL PANEL DE ADMINISTRADOR /ADMIN

# Configuración para archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Para producción
#STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, 'static'),  # Archivos estáticos globales
    #os.path.join(BASE_DIR, 'Farmacia', 'static'),  # Archivos estáticos de la app
#]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]


# settings.py

JAZZMIN_SETTINGS = {
    "site_title": "Albergue Divino Redentor",
    "site_header": "Albergue Divino Redentor",
    "site_brand": "Administración",
    "welcome_sign": "Bienvenido al sistema de administración",
    "copyright": "Albergue Divino Redentor",

    # Personalización de iconos
    "icons": {
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "tu_app.Paciente": "fas fa-user-injured",
        "tu_app.Medicamento": "fas fa-pills",
        "tu_app.ExpedienteMedico": "fas fa-file-medical",
        "tu_app.SalidaMedicamento": "fas fa-file-prescription",
        "tu_app.Medico": "fas fa-user-md",
        "tu_app.CategoriaMedicamento": "fas fa-tags",
    },

    # Tema oscuro
    "theme": "dark",

    # Menú lateral personalizado
    "order_with_respect_to": [
        "tu_app",
        "tu_app.Paciente",
        "tu_app.Medicamento",
        "tu_app.SalidaMedicamento",
    ],

    # Personalización de la UI
    "custom_css": "css/custom_admin.css",
    "custom_js": "js/custom_admin.js",
    "show_ui_builder": True,  # Activa el constructor visual en el admin

    # Enlaces útiles en el menú superior
    "topmenu_links": [
        {"name": "Sitio web", "url": "http://127.0.0.1:8000", "new_window": True},
        {"model": "auth.user"},
    ],
}
