# Generated by Django 5.0.6 on 2025-07-14 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Medicamento',
                'verbose_name_plural': 'Categorías de Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteMedico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('historia_medica', models.TextField(blank=True, verbose_name='Historia Médica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expediente Médico',
                'verbose_name_plural': 'Expedientes Médicos',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='Clave única')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de caducidad')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad en inventario')),
                ('status', models.BooleanField(default=True, verbose_name='Disponible')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.categoriamedicamento')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(verbose_name='Nota médica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='farmacia.expedientemedico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medico', verbose_name='Médico que registra')),
            ],
            options={
                'verbose_name': 'Historia Médica',
                'verbose_name_plural': 'Historias Médicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='expedientemedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.paciente'),
        ),
        migrations.CreateModel(
            name='SalidaMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medico', verbose_name='Médico responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.paciente')),
            ],
            options={
                'verbose_name': 'Salida de Medicamento',
                'verbose_name_plural': 'Salidas de Medicamentos',
            },
        ),
    ]
